
#  Machine Learning
## tutorial Sheet 2
##### Novemeber, 2020  
##### Kenechukwu Ejimofor
###### Data Analytics
###### Matriculation number: 309965
###### Group 1
<center>
<b>
Information Systems and Machine Learning Lab<br>
University of Hildesheim<br>
</b>
<br>
<br>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Universit%C3%A4t_Hildesheim_logo.svg/1200px-Universit%C3%A4t_Hildesheim_logo.svg.png" height="10%" width="10%">
</center>



### Gradient Descent and backtracking line search

In [68]:
def fx(x):
    return  x**4 - (1.3*(x**3))-(1.95*(x**2))+ 4*x+3.65
def diff_fx(x):
    return (4*(x**3))-(3.9*(x**2))-(3.9*x)+4

using a step size (mu) of 0.1 (mu E 0,1) xo = 2. We find the number of iterations by making use of a while loop and count variable to store each iteration

In [77]:
def gradient_descent(fx,xo,alpha,eps):
    temp = xo - alpha * diff_fx(xo)
    count = 0
    while fx(xo) - fx(temp) > eps:
        xo = temp
        temp = xo - alpha * diff_fx(xo)
        count = count+1
    print("The minimum value of fx is:",round(xo)) #ensure the minimum is equal to -1 (assert test can also be used)
    print("The minimum number of iterations required to descend to the minimum at alpha = ",alpha," is:",count)

    


In [78]:
gradient_descent(fx,2,0.1,0.000001)

The minimum value of fx is: -1
The minimum number of iterations required to descend to the minimum at alpha =  0.1  is: 19


Try again with the same step length, but from the startingpointx0= 1.5. Why does it take more iterations to achieve the targetaccuracy, although the starting point is closer to the minimum

In [79]:
gradient_descent(fx,1.5,0.1,0.000001)

The minimum value of fx is: -1
The minimum number of iterations required to descend to the minimum at alpha =  0.1  is: 34


In [214]:
gradient_descent(fx,-0.5,0.1,0.000001)

The minimum value of fx is: -1
The minimum number of iterations required to descend to the minimum at alpha =  0.1  is: 10


Due to the shape(curvature) of the curve(function). when the algorithm approches 1, the steps reduce and smaller steps are taken. But with the larger number i.e xo = 2 larger steps are taken

In [80]:
gradient_descent(fx,-0.5,0.15,0.000001)

The minimum value of fx is: -1
The minimum number of iterations required to descend to the minimum at alpha =  0.15  is: 1


As we can see when xo = -0.5 and alpha = 0.15, the algorithm gets stuck in a forward backward loop

In [84]:
first = diff_fx(-0.5)
first

4.475

Implementing the backtracking line search to compute for optimal step size

In [207]:
def backtracking_line_search(fx,xo,diff_fx,alpha,beta):
    mu = 1
    count =0
    while ((fx(xo-mu*diff_fx(xo)))>fx(xo)- alpha*mu*(diff_fx(xo)**2)):
            mu = beta * mu
            count = count +1
    print("Number of iterations:",count,"\nMu(step size) is equal to:")
    return mu                              

In [208]:
backtracking_line_search(fx,2,diff_fx,0.1,0.5)

Number of iterations: 2 
Mu(step size) is equal to:


0.25

In [209]:
backtracking_line_search(fx,1.5,diff_fx,0.1,0.5)

Number of iterations: 0 
Mu(step size) is equal to:


1

In [210]:
backtracking_line_search(fx,-0.5,diff_fx,0.1,0.5)

Number of iterations: 3 
Mu(step size) is equal to:


0.125

In [211]:
backtracking_line_search(fx,2,diff_fx,0.95,0.5)

Number of iterations: 9 
Mu(step size) is equal to:


0.001953125

In [212]:
backtracking_line_search(fx,1.5,diff_fx,0.95,0.5)

Number of iterations: 7 
Mu(step size) is equal to:


0.0078125

In [213]:
backtracking_line_search(fx,-0.5,diff_fx,0.95,0.5)

Number of iterations: 6 
Mu(step size) is equal to:


0.015625

#### From the above instances we observe that, the larger the alpha the smaller the step size(mu) and vice-versa. alpha selection is imperative in computation of mu(step size)

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import tensorflow as tf
mnist = datasets.load_digits()
X,y = mnist['data'], mnist['target']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2 , random_state = 3116 )

In [30]:
!pip install xgboost

### Catboost Claassification Model

In [36]:
from catboost import CatBoostClassifier as dtc
classifier = dtc()
classifier.fit(X_train,y_train)

Learning rate set to 0.080603
0:	learn: 2.1196781	total: 28.9ms	remaining: 28.9s
1:	learn: 1.9171385	total: 55.5ms	remaining: 27.7s
2:	learn: 1.7929734	total: 82.6ms	remaining: 27.4s
3:	learn: 1.6848851	total: 117ms	remaining: 29.2s
4:	learn: 1.5600966	total: 156ms	remaining: 30.9s
5:	learn: 1.4540439	total: 184ms	remaining: 30.4s
6:	learn: 1.3665901	total: 213ms	remaining: 30.2s
7:	learn: 1.2972452	total: 247ms	remaining: 30.6s
8:	learn: 1.2312610	total: 297ms	remaining: 32.7s
9:	learn: 1.1714368	total: 373ms	remaining: 36.9s
10:	learn: 1.1166274	total: 408ms	remaining: 36.7s
11:	learn: 1.0618421	total: 441ms	remaining: 36.3s
12:	learn: 1.0096599	total: 484ms	remaining: 36.8s
13:	learn: 0.9660262	total: 513ms	remaining: 36.1s
14:	learn: 0.9240909	total: 541ms	remaining: 35.5s
15:	learn: 0.8781271	total: 571ms	remaining: 35.1s
16:	learn: 0.8406420	total: 607ms	remaining: 35.1s
17:	learn: 0.8062171	total: 659ms	remaining: 35.9s
18:	learn: 0.7747189	total: 693ms	remaining: 35.8s
19:	lear

In [37]:
import numpy as np
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred[:20].reshape(-1,1),y_test[:20].reshape(-1,1)), axis = 1))

[[0 0]
 [7 7]
 [0 0]
 [3 3]
 [1 1]
 [7 7]
 [1 1]
 [5 5]
 [2 2]
 [1 1]
 [4 4]
 [3 3]
 [3 3]
 [4 4]
 [2 2]
 [1 8]
 [3 3]
 [0 0]
 [9 9]
 [7 7]]


In [38]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('Accuracy:',accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy: 0.9805555555555555
[[39  0  0  0  1  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0  0]
 [ 0  0 42  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  1  0]
 [ 0  0  0  0 35  0  0  0  0  0]
 [ 0  0  0  0  0 38  0  0  0  0]
 [ 0  0  0  0  0  1 28  0  0  0]
 [ 0  0  0  0  0  0  0 41  0  0]
 [ 0  1  0  1  0  1  0  0 33  0]
 [ 0  0  0  0  0  1  0  0  0 27]]
